[package]
name = "call-by"
version = "0.1.0"
authors = ["Kenny Foner <kwf@boltlabs.io>"]
edition = "2018"
description = "A trick to parameterize functions and traits by the calling convention of their arguments and results"
license = "MIT"
